import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          'Text Translator': 'Text Translator',
          'English': 'English',
          'Languages': 'Languages',
          'Privacy Policy': 'Privacy Policy',
          'About Us': 'About Us',
          'Contact Us': 'Contact Us',
          'Urdu': 'Urdu',
          'Hindi': 'Hindi',
          'Arabic': 'Arabic',
          'Spanish': 'Spanish',
          'French': 'French',
          'German': 'German',
          'Chinese': 'Chinese',
          'Portuguese': 'Portuguese',
          'Bengali': 'Bengali',
          'Russian': 'Russian',
          'Japanese': 'Japanese',
          'Korean': 'Korean',
          'Turkish': 'Turkish',
          'Indonesian': 'Indonesian',
          'Select language': 'Select language',
          'cancel': 'Cancel',
          'Write text here': 'Write text here',
          'Translate': 'Translate',
          'OCR': 'OCR',
          'Speech to Text': 'Speech to Text',
          'Press the button and start speaking':
              'Press the button and start speaking',
          'Con': 'Conversation',
          'Translation App': 'Translation App',
          'My Favorites': 'My Favorites',
          'Share App': 'Share App',
          'OCR Text Scanner': 'OCR Text Scanner',
          'Saved': 'Saved',
          'No Text Available Press the button  \n\nto select image':
              'No Text Available Press the button  \n\nto select image',
          'Translation': 'Translation',
          'No Record Found': 'No Record Found',
          'Text Copied': 'Text Copied',
          'Text Cleared': 'Text Cleared',
          'Clear': 'Clear',
          'Text deleted': 'Text deleted',
          'Added to favorite': 'Added to favorite',
          'Removed from favorite': 'Removed from favorite',
          'Next': 'Next',
          'Skip': 'Skip',
          'Welcome to Translation Pro': 'Welcome to Translation Pro',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered',
          'Scan and Translate': 'Scan and Translate',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text',
          'Conversation Mode': 'Conversation Mode',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!"
        },
        //HINDI LANGUAGE
        'hi_IN': {
          'Next': 'अगला',
          'Skip': 'छोडना',
          'Welcome to Translation Pro': 'अनुवाद प्रो में आपका स्वागत है',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'केवल कुछ टैप के साथ पाठ को एकाधिक में अनुवाद करें। चाहे आप विदेश यात्रा कर रहे हों या किसी अन्य भाषा में किसी के साथ संवाद कर रहे हों, अनुवाद प्रो ने आपको कवर किया है',
          'Scan and Translate': 'स्कैन और अनुवाद करें',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'छवियों और दस्तावेज़ों से पाठ निकालने के लिए हमारे OCR स्कैनर का उपयोग करें, और उनका तुरंत अनुवाद करें। यह शक्तिशाली विशेषता संकेतों, मेनू और अन्य पाठ का अनुवाद करना आसान बनाती है',
          'Conversation Mode': 'बातचीत मोड',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "किसी ऐसे व्यक्ति से बातचीत करने की आवश्यकता है जो भिन्न भाषा बोलता हो? अनुवाद प्रो का वार्तालाप मोड आपको रीयल-टाइम में बोलने और अनुवाद करने देता है। बस भाषाएं चुनें और बात करना शुरू करें!",
          'Text Translator': 'पाठ अनुवादक',
          'English': 'अंग्रेज़ी',
          'Languages': 'बोली',
          'Privacy Policy': 'गोपनीयता नीति',
          'About Us': 'हमारे बारे में',
          'Contact Us': 'संपर्क करें',
          'Urdu': 'उर्दू',
          'Hindi': 'हिंदी',
          'Arabic': 'अरबी',
          'Spanish': 'स्पैनिश',
          'French': 'फ्रेंच',
          'German': 'जर्मन',
          'Chinese': 'चीनी',
          'Portuguese': 'पुर्तगाली',
          'Bengali': 'बंगाली',
          'Russian': 'रूसी',
          'Japanese': 'जापानी',
          'Korean': 'कोरियाई',
          'Turkish': 'तुर्की',
          'Indonesian': 'इन्डोनेशियाई',
          'Select language': 'भाषा चुने',
          'cancel': 'रद्द करना',
          'Write text here': 'यहाँ टेक्स्ट लिखें',
          'Translate': 'अनुवाद',
          'OCR': 'ओसीआर',
          'Speech to Text': 'भाषण से पाठ',
          'Press the button and start speaking': 'बटन दबाएं और बोलना शुरू करें',
          'Con': 'Conversation',
          'Translation App': 'अनुवाद ऐप',
          'My Favorites': 'मेरे प्रिय',
          'Share App': 'ऐप शेयर करें',
          'OCR Text Scanner': 'ओसीआर पाठ स्कैनर',
          'Saved': 'बचाया',
          'No Text Available Press the button  \n\nto select image':
              'कोई टेक्स्ट उपलब्ध नहीं छवि चुनने के लिए \n\n बटन दबाएँ',
          'Translation': 'अनुवाद',
          'No Record Found': 'कोई रिकॉर्ड नहीं मिला',
          'Text Copied': 'टेक्स्ट कॉपी किया गया',
          'Text Cleared': 'पाठ साफ़ किया गया',
          'Clear': 'साफ़',
          'Text deleted': 'पाठ हटाया गया',
          'Added to favorite': 'पसंदीदा में जोड़ा गया',
          'Removed from favorite': 'पसंदीदा से निकाला गया'
        },

//Urdu language
        'ur_PK': {
          'Next': 'اگلے',
          'Skip': 'چھوڑ دو',
          'Welcome to Translation Pro': 'ترجمہ پرو میں خوش آمدید',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'صرف چند ٹیپس کے ساتھ متن کا متعدد میں ترجمہ کریں۔ چاہے آپ بیرون ملک سفر کر رہے ہوں یا کسی سے دوسری زبان میں بات چیت کر رہے ہوں، Translation Pro نے آپ کو کور کر لیا ہے۔',
          'Scan and Translate': 'اسکین اور ترجمہ کریں۔',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'تصاویر اور دستاویزات سے متن نکالنے کے لیے ہمارا OCR سکینر استعمال کریں، اور ان کا فوری ترجمہ کریں۔ یہ طاقتور خصوصیت علامات، مینو اور دیگر متن کا ترجمہ کرنا آسان بناتی ہے۔',
          'Conversation Mode': 'گفتگو کا موڈ',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "کسی کے ساتھ بات چیت کرنے کی ضرورت ہے جو ایک مختلف زبان بولتا ہے؟ ترجمہ پرو کا گفتگو کا موڈ آپ کو حقیقی وقت میں بولنے اور ترجمہ کرنے دیتا ہے۔ بس زبانیں منتخب کریں اور بات کرنا شروع کریں!",
          'Removed from favorite': 'پسندیدہ سے ہٹا دیا گیا',
          'Text Copied': 'متن کاپی ہو گیا۔',
          'Text Cleared': 'متن صاف ہو گیا۔',
          'Clear': 'صاف',
          'Text deleted': 'متن حذف کر دیا گیا۔',
          'Added to favorite': 'پسندیدہ میں شامل کیا گیا۔',
          'No Record Found': 'کوئی ریکارڈ نہیں ملا',
          'Translation': 'ترجمہ',
          'Saved': 'محفوظ کیا گیا۔',
          'Con': 'بات چیت',
          'Press the button and start speaking':
              'بٹن دبائیں اور بولنا شروع کریں۔',
          'Speech to Text': 'متن سے تقریر',
          'No Text Available Press the button  \n\nto select image':
              'کوئی متن دستیاب نہیں تصویر کو منتخب \nکرنے کے لیے بٹن دبائیں۔',
          'OCR Text Scanner': 'OCR ٹیکسٹ سکینر',
          'Write text here': 'یہاں متن لکھیں۔',
          'My Favorites': 'میرے پسندیدہ',
          'Text Translator': 'متن مترجم',
          'English': 'انگریزی',
          'Languages': 'زبان',
          'Privacy Policy': 'رازداری کی پالیسی',
          'About Us': 'ہمارے بارے میں',
          'Contact Us': 'ہم سے رابطہ کریں۔',
          'Urdu': 'اردو',
          'Hindi': 'ہندی',
          'Arabic': 'عربی',
          'Spanish': 'ہسپانوی',
          'French': 'فرانسیسی',
          'German': 'جرمن',
          'Chinese': 'چینی',
          'Portuguese': 'پرتگالی',
          'Bengali': 'بنگالی',
          'Russian': 'روسی',
          'Japanese': 'جاپانی',
          'Korean': 'کورین',
          'Turkish': 'ترکی',
          'Indonesian': 'انڈونیشین',
          'Select language': 'زبان منتخب کریں۔',
          'cancel': 'منسوخ کریں۔',
          'Translation App': 'ترجمہ ایپ',
        },
        // // Arabic language
        'ar_AE': {
          'Next': 'التالي',
          'Skip': 'يتخطى',
          'Welcome to Translation Pro': 'مرحبًا بك في Translation Pro',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'ترجمة النص إلى عدة نقرات فقط. سواء كنت مسافرًا للخارج أو تتواصل مع شخص ما بلغة أخرى ، فإن Translation Pro يخبرك',
          'Scan and Translate': 'مسح وترجمة',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'استخدم ماسح OCR لاستخراج النص من الصور والمستندات وترجمتها على الفور. تسهل هذه الميزة القوية ترجمة الإشارات والقوائم والنصوص الأخرى',
          'Conversation Mode': 'وضع المحادثة',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "هل تحتاج إلى إجراء محادثة مع شخص يتحدث لغة مختلفة؟ يتيح لك وضع المحادثة في Translation Pro التحدث والترجمة في الوقت الفعلي. ما عليك سوى اختيار اللغات والبدء في التحدث!",
          'Text Translator': 'مترجم نصي',
          'English': 'إنجليزي',
          'Languages': 'اللهجة',
          'Privacy Policy': 'سياسة الخصوصية',
          'About Us': 'معلومات عنا',
          'Contact Us': 'اتصل بنا',
          'Urdu': 'الأردية',
          'Hindi': 'هندي',
          'Arabic': 'عربي',
          'Spanish': 'الأسبانية',
          'French': 'فرنسي',
          'German': 'ألمانية',
          'Chinese': 'صينى',
          'Portuguese': 'البرتغالية',
          'Bengali': 'البنغالية',
          'Russian': 'الروسية',
          'Japanese': 'اليابانية',
          'Korean': 'الكورية',
          'Turkish': 'اللغة التركية',
          'Indonesian': 'الأندونيسية',
          'Select language': 'اختار اللغة',
          'cancel': 'يلغي',
          'Write text here': 'اكتب نصًا هنا',
          'Translate': 'يترجم',
          'OCR': 'OCR',
          'Speech to Text': 'خطاب إلى نص',
          'Press the button and start speaking':
              'Press the button and start speaking',
          'Con': 'محادثة',
          'Translation App': 'تطبيق الترجمة',
          'My Favorites': 'مفضلتي',
          'Share App': 'شارك التطبيق',
          'OCR Text Scanner': 'الماسح الضوئي للنص OCR',
          'Saved': 'Saved',
          'No Text Available Press the button  \n\nto select image':
              'لا يتوفر نص اضغط على الزر \n \n لتحديد الصورة',
          'Translation': 'Translation',
          'No Record Found': 'لا يوجد سجلات',
          'Text Copied': 'تم نسخ النص',
          'Text Cleared': 'تم مسح النص',
          'Clear': 'واضح',
          'Text deleted': 'تم حذف النص',
          'Added to favorite': 'تمت الإضافة إلى المفضلة',
          'Removed from favorite': 'تمت إزالته من المفضلة'
        },

        // //spanish language
        'es_AR': {
          'Next': 'Próxima',
          'Skip': 'Saltar',
          'Welcome to Translation Pro': 'Bienvenido a Translation Pro',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'Traduce texto a múltiples con solo unos pocos toques. Ya sea que viaje al extranjero o se comunique con alguien en otro idioma, Translation Pro lo tiene cubierto',
          'Scan and Translate': 'Escanear y traducir',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'Utilice nuestro escáner OCR para extraer texto de imágenes y documentos y traducirlos al instante. Esta potente función facilita la traducción de letreros, menús y otros textos.',
          'Conversation Mode': 'Modo de conversación',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "¿Necesita tener una conversación con alguien que habla un idioma diferente? El modo de conversación de Translation Pro le permite hablar y traducir en tiempo real. ¡Solo selecciona los idiomas y comienza a hablar!",
          'Text Translator': 'Traductora de texto',
          'English': 'Inglés',
          'Languages': 'Idiomas',
          'Privacy Policy': 'política de privacidad',
          'About Us': 'Sobre nosotros',
          'Contact Us': 'Contacta con nosotras',
          'Urdu': 'urdu',
          'Hindi': 'hindi',
          'Arabic': 'Arábica',
          'Spanish': 'Español',
          'French': 'Francés',
          'German': 'Alemán',
          'Chinese': 'Chino',
          'Portuguese': 'Portugués',
          'Bengali': 'bengalí',
          'Russian': 'Ruso',
          'Japanese': 'Japonés',
          'Korean': 'Coreano',
          'Turkish': 'Turco',
          'Indonesian': 'Indonesio',
          'Select language': 'Seleccione el idioma',
          'cancel': 'Cancelar',
          'Write text here': 'Escribe texto aquí',
          'Translate': 'Traducir',
          'OCR': 'OCR',
          'Speech to Text': 'Dictado a texto',
          'Press the button and start speaking':
              'Pulsa el botón y empieza a hablar',
          'Con': 'Conversación',
          'Translation App': 'Aplicación de traducción',
          'My Favorites': 'Mis favoritos',
          'Share App': 'Compartir aplicación',
          'OCR Text Scanner': 'Escáner de texto OCR',
          'Saved': 'Salvado',
          'No Text Available Press the button  \n\nto select image':
              'No hay texto disponible Pulse el botón \n\npara seleccionar la imagen',
          'Translation': 'Traducción',
          'No Record Found': 'ningún record fue encontrado',
          'Text Copied': 'Texto copiado',
          'Text Cleared': 'Texto borrado',
          'Clear': 'Claro',
          'Text deleted': 'Texto eliminado',
          'Added to favorite': 'Agregado a favoritos',
          'Removed from favorite': 'Eliminado de favoritos'
        },

        // //French language
        'fr_BE': {
          'Next': 'Suivant',
          'Skip': 'Sauter',
          'Welcome to Translation Pro': 'Bienvenue dans Traduction Pro',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'Traduisez du texte en plusieurs en quelques clics. Que vous voyagiez à létranger ou que vous communiquiez avec quelquun dans une autre langue, Translation Pro vous couvre',
          'Scan and Translate': 'Numériser et traduire',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'Utilisez notre scanner OCR pour extraire le texte des images et des documents et les traduire instantanément. Cette fonctionnalité puissante facilite la traduction des panneaux, des menus et dautres textes',
          'Conversation Mode': 'Conversation en mode',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "Besoin d'avoir une conversation avec quelqu'un qui parle une autre langue ? Le mode conversation de Translation Pro vous permet de parler et de traduire en temps réel. Sélectionnez simplement les langues et commencez à parler !",
          'Text Translator': 'Traducteur de texte',
          'English': 'Anglais',
          'Languages': 'Langages',
          'Privacy Policy': 'politique de confidentialité',
          'About Us': 'À propos de nous',
          'Contact Us': 'Contactez-nous',
          'Urdu': 'Ourdou',
          'Hindi': 'hindi',
          'Arabic': 'arabe',
          'Spanish': 'Espagnol',
          'French': 'Français',
          'German': 'Allemande',
          'Chinese': 'Chinois',
          'Portuguese': 'Portugais',
          'Bengali': 'bengali',
          'Russian': 'russe',
          'Japanese': 'Japonais',
          'Korean': 'Coréen',
          'Turkish': 'Turc',
          'Indonesian': 'Indonésien',
          'cancel': 'Annuler',
          'Select language': 'Select language',
          'Write text here': 'Écrivez le texte ici',
          'Translate': 'Traduire',
          'OCR': 'OCR',
          'Speech to Text': 'Discours au texte',
          'Press the button and start speaking':
              'Appuyez sur le bouton et commencez à parler',
          'Con': 'Conversation',
          'Translation App': 'Application de traduction',
          'My Favorites': 'Mes favoris',
          'Share App': 'Partager lapplication',
          'OCR Text Scanner': 'Scanner de texte OCR',
          'Saved': 'Enregistré',
          'No Text Available Press the button  \n\nto select image':
              'Aucun texte disponible Appuyez sur le bouton \n\npour sélectionner limage',
          'Translation': 'Traduction',
          'No Record Found': 'Aucun Enregistrement Trouvé',
          'Text Copied': 'Texte copié',
          'Text Cleared': 'Texte effacé',
          'Clear': 'Clair',
          'Text deleted': 'Texte supprimé',
          'Added to favorite': 'Ajouté aux favoris',
          'Removed from favorite': 'Supprimé des favoris'
        },

        // //German language
        'de_AT': {
          'Next': 'Nächste',
          'Skip': 'Überspringen',
          'Welcome to Translation Pro': 'Willkommen bei Translation Pro',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'Übersetzen Sie Text mit nur wenigen Fingertipps in mehrere. Egal, ob Sie ins Ausland reisen oder mit jemandem in einer anderen Sprache kommunizieren, Translation Pro ist für Sie da',
          'Scan and Translate': 'Scannen und übersetzen',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'Verwenden Sie unseren OCR-Scanner, um Text aus Bildern und Dokumenten zu extrahieren und sofort zu übersetzen. Diese leistungsstarke Funktion erleichtert das Übersetzen von Schildern, Speisekarten und anderem Text',
          'Conversation Mode': 'Gesprächsmodus',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "Müssen Sie sich mit jemandem unterhalten, der eine andere Sprache spricht? Im Konversationsmodus von Translation Pro können Sie in Echtzeit sprechen und übersetzen. Wählen Sie einfach die Sprachen aus und fangen Sie an zu sprechen!",
          'Text Translator': 'Textübersetzer',
          'Languages': 'Sprachen',
          'Privacy Policy': 'Datenschutz-Bestimmungen',
          'About Us': 'Über uns', //from there
          'Contact Us': 'Kontaktiere uns',
          'Urdu': 'Urdu',
          'English': 'Englisch',
          'Hindi': 'Hindi',
          'Arabic': 'Arabisch',
          'Spanish': 'Spanisch',
          'French': 'Französisch',
          'German': 'Deutsch',
          'Chinese': 'Chinesisch',
          'Portuguese': 'Portuguese',
          'Bengali': 'Bengali',
          'Russian': 'Russisch',
          'Japanese': 'japanisch',
          'Korean': 'Koreanisch',
          'Turkish': 'Türkisch',
          'Indonesian': 'Indonesisch',
          'Select the language': 'Wählen Sie die Sprache aus',
          'Select language': 'Sprache auswählen',
          'cancel': 'Stornieren',
          'Write text here': 'Schreiben Sie hier Text',
          'Translate': 'Übersetzen',
          'OCR': 'OCR',
          'Speech to Text': 'Sprache zu Text',
          'Press the button and start speaking':
              'Drücken Sie die Taste und beginnen Sie zu sprechen',
          'Con': 'Gespräch',
          'Translation App': 'Übersetzungs-App',
          'My Favorites': 'Meine Favoriten',
          'Share App': 'App teilen',
          'OCR Text Scanner': 'OCR-Textscanner',
          'Saved': 'Gerettet',
          'No Text Available Press the button  \n\nto select image':
              'Kein Text verfügbar Drücken Sie die Taste \n\num ein Bild auszuwählen',
          'Translation': 'Übersetzung',
          'No Record Found': 'Kein Eintrag gefunden',
          'Text Copied': 'Texte kopiert',
          'Text Cleared': 'Text gelöscht',
          'Clear': 'Klar',
          'Text deleted': 'Texte gelöscht',
          'Added to favorite': 'Zu Favoriten hinzugefügt',
          'Removed from favorite': 'Aus Favoriten entfernt',
        },
        // //chinese language
        'zh_Hans': {
          'Text Translator': '文本翻譯器',
          'Languages': '語言',
          'Privacy Policy': '隱私政策',
          'About Us': '關於我們',
          'Contact Us': '聯繫我們',
          'Urdu': '烏爾都語',
          'English': '英語',
          'Hindi': '印地語',
          'Arabic': '阿拉伯',
          'Spanish': '西班牙語',
          'French': '法語',
          'German': '德語',
          'Chinese': '中國人',
          'Portuguese': '葡萄牙語',
          'Bengali': '孟加拉',
          'Russian': '俄語',
          'Japanese': '日本人',
          'Korean': '韓國人',
          'Turkish': '土耳其',
          'Indonesian': '印度尼西亞',
          'Select the language': '選擇語言',
          'cancel': '取消',
          'Select language': '選擇語言',
          'Write text here': '在這裡寫文字',
          'Translate': '翻譯',
          'OCR': '文字識別',
          'Speech to Text': '語音轉文字',
          'Press the button and start speaking': '按下按鈕開始說話',
          'Con': '對話',
          'Translation App': '翻譯應用',
          'My Favorites': '我最喜愛的',
          'Share App': '分享應用',
          'OCR Text Scanner': 'OCR 文本掃描儀',
          'Saved': '已保存',
          'No Text Available Press the button  \n\nto select image':
              '沒有可用的文本按按鈕\n\n選擇圖像',
          'Translation': '翻譯',
          'No Record Found': '沒有找到記錄',
          'Text Copied': '文本已復制',
          'Text Cleared': '文本已清除',
          'Clear': '清除',
          'Text deleted': '文本已刪除',
          'Added to favorite': '添加到收藏夾',
          'Removed from favorite': '從收藏夾中刪除',
          'Next': '下一個',
          'Skip': '跳過',
          'Welcome to Translation Pro': '歡迎使用 Translation Pro',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              '只需輕點幾下，即可將文本翻譯成多個文本。無論您是出國旅行還是與使用另一種語言的人交流，Translation Pro 都能滿足您的需求',
          'Scan and Translate': '掃描並翻譯',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              '使用我們的 OCR 掃描儀從圖像和文檔中提取文本，並立即進行翻譯。這一強大的功能使翻譯標誌、菜單和其他文本變得容易',
          'Conversation Mode': '對話模式',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              '需要與說不同語言的人交談？Translation Pro 的對話模式讓您可以實時說話和翻譯。只需選擇語言並開始交談'
        },
        // //Portugal language
        'pt_AO': {
          'Text Translator': 'Tradutor de texto',
          'Languages': 'línguas',
          'Privacy Policy': 'Política de Privacidade',
          'About Us': 'Sobre nós',
          'Contact Us': 'Contate-nos',
          'Urdu': 'urdu',
          'English': 'Inglês',
          'Hindi': 'hindi',
          'Arabic': 'árabe',
          'Spanish': 'Espanhol',
          'French': 'Francês',
          'German': 'Alemão',
          'Chinese': 'chinês',
          'Portuguese': 'Português',
          'Bengali': 'bengali',
          'Russian': 'Russo',
          'Japanese': 'japonês',
          'Korean': 'Coreano',
          'Turkish': 'Turco',
          'Indonesian': 'Indonésio',
          'Select language': 'Select language',
          'cancel': 'Cancelar',
          'Write text here': 'Escreva o texto aqui',
          'Translate': 'Traduzir',
          'OCR': 'OCR',
          'Speech to Text': 'Fala para Texto',
          'Press the button and start speaking':
              'Pressione o botão e comece a falar',
          'Con': 'Conversação',
          'Translation App': 'Aplicativo de tradução',
          'My Favorites': 'Meus favoritos',
          'Share App': 'Compartilhe o aplicativo',
          'OCR Text Scanner': 'Scanner de texto OCR',
          'Saved': 'Salvou',
          'No Text Available Press the button  \n\nto select image':
              'Nenhum texto disponível Pressione o botão \n\npara selecionar a imagem',
          'Translation': 'Tradução',
          'No Record Found': 'Nenhum Registro Encontrado',
          'Text Copied': 'Texto copiado',
          'Text Cleared': 'Texto limpo',
          'Clear': 'Claro',
          'Text deleted': 'Texto deletado',
          'Added to favorite': 'Adicionado aos favoritos',
          'Removed from favorite': 'Removido dos favoritos',
          'Next': 'Próximo',
          'Skip': 'Pular',
          'Welcome to Translation Pro': 'Bem-vindo ao Translation Pro',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'Traduzir texto em vários com apenas alguns toques. Esteja você viajando para o exterior ou se comunicando com alguém em outro idioma, o Translation Pro o protege',
          'Scan and Translate': 'Escanear e Traduzir',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'Use nosso scanner OCR para extrair texto de imagens e documentos e traduzi-los instantaneamente. Esse poderoso recurso facilita a tradução de sinais, menus e outros textos',
          'Conversation Mode': 'Modo de conversação',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "Precisa conversar com alguém que fala um idioma diferente? O modo de conversação do Translation Pro permite que você fale e traduza em tempo real. Basta selecionar os idiomas e começar a falar!"
        },
        ////Bengali language
        'bn_BD': {
          'Text Translator': 'পাঠ্য অনুবাদক',
          'Languages': 'ভাষা',
          'Privacy Policy': 'গোপনীয়তা নীতি',
          'About Us': 'আমাদের সম্পর্কে',
          'Contact Us': 'যোগাযোগ করুন',
          'Urdu': 'উর্দু',
          'English': 'ইংরেজি',
          'Hindi': 'হিন্দি',
          'Arabic': 'আরবি',
          'Spanish': 'স্পেনীয়',
          'French': 'ফরাসি',
          'German': 'জার্মান',
          'Chinese': 'চাইনিজ',
          'Portuguese': 'পর্তুগীজ',
          'Bengali': 'বাংলা',
          'Russian': 'রাশিয়ান',
          'Japanese': 'জাপানিজ',
          'Korean': 'কোরিয়ান',
          'Turkish': 'তুর্কি',
          'Indonesian': 'ইন্দোনেশিয়ান',
          'Select the language': 'ভাষা নির্বাচন করুন',
          'cancel': 'বাতিল করুন',
          'Select language': 'ভাষা নির্বাচন কর',
          'Write text here': 'এখানে পাঠ্য লিখুন',
          'Translate': 'অনুবাদ করা',
          'OCR': 'OCR',
          'Speech to Text': 'স্পিচ টু টেক্সট',
          'Press the button and start speaking':
              'বোতাম টিপুন এবং কথা বলা শুরু করুন',
          'Con': 'কথোপকথন',
          'Translation App': 'অনুবাদ অ্যাপ',
          'My Favorites': 'আমার পছন্দের',
          'Share App': 'অ্যাপ্লিকেশন ভাগ করা',
          'OCR Text Scanner': 'ওসিআর টেক্সট স্ক্যানার',
          'Saved': 'সংরক্ষিত',
          'No Text Available Press the button  \n\nto select image':
              'কোন টেক্সট উপলভ্য নয় বোতাম টিপুন \n\nছবি নির্বাচন করতে',
          'Translation': 'অনুবাদ',
          'No Record Found': 'পাওয়া কোন রেকর্ড',
          'Text Copied': 'পাঠ্য অনুলিপি করা হয়েছে',
          'Text Cleared': 'পাঠ্য সাফ',
          'Clear': 'পরিষ্কার',
          'Text deleted': 'পাঠ্য মুছে ফেলা হয়েছে',
          'Added to favorite': 'প্রিয়তে যোগ করা হয়েছে',
          'Removed from favorite': 'প্রিয় থেকে সরানো হয়েছে',
          'Next': 'পরবর্তী',
          'Skip': 'এড়িয়ে যান',
          'Welcome to Translation Pro': 'অনুবাদ প্রোতে স্বাগতম',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'মাত্র কয়েকটি ট্যাপ দিয়ে একাধিক টেক্সট অনুবাদ করুন। আপনি বিদেশ ভ্রমণ করছেন বা অন্য ভাষায় কারও সাথে যোগাযোগ করছেন, অনুবাদ প্রো আপনাকে কভার করেছে',
          'Scan and Translate': 'স্ক্যান এবং অনুবাদ করুন',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'ছবি এবং নথি থেকে পাঠ্য বের করতে এবং তাৎক্ষণিকভাবে অনুবাদ করতে আমাদের OCR স্ক্যানার ব্যবহার করুন। এই শক্তিশালী বৈশিষ্ট্যটি লক্ষণ, মেনু এবং অন্যান্য পাঠ্য অনুবাদ করা সহজ করে তোলে',
          'Conversation Mode': 'কথোপকথন মোড',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "একটি ভিন্ন ভাষায় কথা বলে এমন কারো সাথে কথোপকথন করা দরকার? অনুবাদ প্রো-এর কথোপকথন মোড আপনাকে রিয়েল-টাইমে কথা বলতে এবং অনুবাদ করতে দেয়। শুধু ভাষা নির্বাচন করুন এবং কথা বলা শুরু করুন!"
        },
        // //Russian language
        'ru_RU': {
          'Text Translator': 'Переводчик текста',
          'Languages': 'Языки',
          'Privacy Policy': 'Политика конфиденциальности',
          'About Us': 'О нас',
          'Contact Us': 'Связаться с нами',
          'Urdu': 'урду',
          'English': 'Английский',
          'Hindi': 'хинди',
          'Arabic': 'Arabic',
          'Spanish': 'испанский',
          'French': 'Французский',
          'German': 'Немецкий',
          'Chinese': 'Китайский',
          'Portuguese': 'португальский',
          'Bengali': 'бенгальский',
          'Russian': 'Русский',
          'Japanese': 'Японский',
          'Korean': 'Корейский',
          'Turkish': 'турецкий',
          'Indonesian': 'индонезийский',
          'Select the language': 'Выберите язык',
          'cancel': 'Отмена',
          'Select language': 'Выберите язык',
          'Write text here': 'Напишите текст здесь',
          'Translate': 'Переводить',
          'OCR': 'OCR',
          'Speech to Text': 'Речь в текст',
          'Press the button and start speaking':
              'Нажмите кнопку и начните говорить',
          'Con': 'Беседа',
          'Translation App': 'Приложение для перевода',
          'My Favorites': 'Мои любимые',
          'Share App': 'Поделиться приложением',
          'OCR Text Scanner': 'OCR текстовый сканер',
          'Saved': 'Сохранено',
          'No Text Available Press the button  \n\nto select image':
              'Текст недоступен. Нажмите кнопку \n\n, чтобы выбрать изображение',
          'Translation': 'Перевод',
          'No Record Found': 'Запись не найдена',
          'Text Copied': 'Текст скопирован',
          'Text Cleared': 'Текст очищен',
          'Clear': 'Прозрачный',
          'Text deleted': 'Текст удален',
          'Added to favorite': 'Добавлено в избранное',
          'Removed from favorite': 'Удалено из избранного',
          'Next': 'Следующий',
          'Skip': 'Пропускать',
          'Welcome to Translation Pro': 'Добро пожаловать в Перевод Про',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'Переведите текст в несколько с помощью всего нескольких нажатий. Путешествуете ли вы за границу или общаетесь с кем-то на другом языке, Translation Pro поможет ва',
          'Scan and Translate': 'Отсканируй и переведи',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'Используйте наш OCR-сканер для извлечения текста из изображений и документов и мгновенного их перевода. Эта мощная функция позволяет легко переводить вывески, меню и другой текст.',
          'Conversation Mode': 'Режим разговора',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "Нужно поговорить с кем-то, кто говорит на другом языке? Режим разговора в Translation Pro позволяет говорить и переводить в режиме реального времени. Просто выберите языки и начните говорить!"
        },
        // //Japanese language

        'ja_JP': {
          'Text Translator': 'テキスト翻訳者',
          'Languages': '言語',
          'Privacy Policy': 'プライバシーポリシー',
          'About Us': '私たちに関しては',
          'Contact Us': 'お問い合わせ',
          'Urdu': 'ウルドゥー語',
          'English': '英語',
          'Hindi': 'ヒンディー語',
          'Arabic': 'アラビア語',
          'Spanish': 'スペイン語',
          'French': 'フランス語',
          'German': 'ドイツ人',
          'Chinese': '中国語',
          'Portuguese': 'ポルトガル語',
          'Bengali': 'ベンガル語',
          'Russian': 'ロシア',
          'Japanese': '日本',
          'Korean': '韓国語',
          'Turkish': 'トルコ語',
          'Indonesian': 'インドネシア語',
          'Select the language': '言語を選択',
          'cancel': 'キャンセル',
          'Select language': '言語を選択する',
          'Write text here': 'ここにテキストを書く',
          'Translate': '翻訳',
          'OCR': 'OCR',
          'Speech to Text': '音声からテキストへ',
          'Press the button and start speaking': 'ボタンを押して話し始めてください',
          'Con': '会話',
          'Translation App': '翻訳アプリ',
          'My Favorites': '私のお気に入り',
          'Share App': 'アプリを共有',
          'OCR Text Scanner': 'OCRテキストスキャナ',
          'Saved': '保存しました',
          'No Text Available Press the button  \n\nto select image':
              '利用可能なテキストがありません\n\nボタンを押して画像を選択してください',
          'Translation': '翻訳',
          'No Record Found': 'レコードが見つかりません',
          'Text Copied': 'テキストをコピーしました',
          'Text Cleared': 'テキストがクリアされました',
          'Clear': 'クリア',
          'Text deleted': 'テキストを削除しました',
          'Added to favorite': 'お気に入りに追加',
          'Removed from favorite': 'お気に入りから削除',
          'Next': '次',
          'Skip': 'スキップ',
          'Welcome to Translation Pro': '翻訳プロへようこそ',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              '数回タップするだけでテキストを複数に翻訳します。海外旅行でも、外国語でのコミュニケーションでも、Translation Pro が対応します。',
          'Scan and Translate': 'スキャンして翻訳',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              '当社の OCR スキャナーを使用して、画像やドキュメントからテキストを抽出し、即座に翻訳します。この強力な機能により、標識、メニュー、その他のテキストを簡単に翻訳できます',
          'Conversation Mode': '会話モード',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "異なる言語を話す人と会話する必要がありますか? Translation Pro の会話モードでは、リアルタイムで話したり翻訳したりできます。言語を選択して話し始めるだけです。"
        },

        // //Korean language
        'ko_KR': {
          'Text Translator': '텍스트 번역기',
          'Languages': '언어',
          'Privacy Policy': '개인 정보 정책',
          'About Us': '회사 소개',
          'Contact Us': '문의하기',
          'Urdu': '우르두어',
          'English': '영어',
          'Hindi': '힌디 어',
          'Arabic': '아라비아 말',
          'Spanish': '스페인의',
          'French': '프랑스 국민',
          'German': '독일 사람',
          'Chinese': '중국인',
          'Portuguese': '포르투갈 인',
          'Bengali': '벵골 사람',
          'Russian': '러시아인',
          'Japanese': '일본어',
          'Korean': '한국인',
          'Turkish': '터키어',
          'Indonesian': '인도네시아 인',
          'Select the language': '언어를 선택하세요',
          'cancel': '취소',
          'Select language': '언어 선택',
          'Write text here': '여기에 텍스트 쓰기',
          'Translate': '번역하다',
          'OCR': 'OCR',
          'Speech to Text': '말을 텍스트로',
          'Press the button and start speaking': '버튼을 누르고 말하기 시작',
          'Con': '대화',
          'Translation App': '번역 앱',
          'My Favorites': '내가 좋아하는 것들',
          'Share App': '앱 공유',
          'OCR Text Scanner': 'OCR 텍스트 스캐너',
          'Saved': '저장됨',
          'No Text Available Press the button  \n\nto select image':
              '사용할 수 있는 텍스트가 없습니다. 이미지를 선택하려면 \n\n버튼을 누르세요.',
          'Translation': '번역',
          'No Record Found': '기록을 찾을 수 없습니다',
          'Text Copied': '텍스트 복사됨',
          'Text Cleared': '텍스트 삭제됨',
          'Clear': '분명한',
          'Text deleted': '텍스트 삭제됨',
          'Added to favorite': '즐겨찾기에 추가',
          'Removed from favorite': '즐겨찾기에서 삭제',
          'Next': '다음',
          'Skip': '건너뛰다',
          'Welcome to Translation Pro': '번역 프로에 오신 것을 환영합니다',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              '몇 번의 탭만으로 텍스트를 여러 개로 번역하세요. 해외 여행을 가거나 다른 언어로 누군가와 의사소통을 하든, Translation Pro가 도와드립니다.',
          'Scan and Translate': '스캔 및 번역',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'OCR 스캐너를 사용하여 이미지와 문서에서 텍스트를 추출하고 즉시 번역하세요. 이 강력한 기능을 사용하면 표지판, 메뉴 및 기타 텍스트를 쉽게 번역할 수 있습니다.',
          'Conversation Mode': '대화 모드',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "다른 언어를 사용하는 사람과 대화가 필요하세요? Translation Pro의 대화 모드를 사용하면 실시간으로 말하고 번역할 수 있습니다. 언어를 선택하고 대화를 시작하세요!"
        },

        // //Turkish language

        'tr_TR': {
          'Text Translator': 'Metin Tercümanı',
          'Languages': 'Diller',
          'Privacy Policy': 'Gizlilik Politikası',
          'About Us': 'Hakkımızda',
          'Contact Us': 'Bize Ulaşın',
          'Urdu': 'Urduca',
          'English': 'İngilizce',
          'Hindi': 'Hintçe',
          'Arabic': 'Arapça',
          'Spanish': 'İspanyol',
          'French': 'Fransızca',
          'German': 'Almanca',
          'Chinese': 'Çince',
          'Portuguese': 'Portekizce',
          'Bengali': 'Bengalce',
          'Russian': 'Rusça',
          'Japanese': 'Japonca',
          'Korean': 'Koreli',
          'Turkish': 'Türkçe',
          'Indonesian': 'Endonezya dili',
          'Select the language': 'dili seçin',
          'cancel': 'İptal etmek',
          'Select language': 'Dil Seçin',
          'Write text here': 'Metni buraya yaz',
          'Translate': 'Çevirmek',
          'OCR': 'OCR',
          'Speech to Text': 'Konuşmadan yazıya',
          'Press the button and start speaking':
              'Düğmeye basın ve konuşmaya başlayın',
          'Con': 'Konuşma',
          'Translation App': 'Çeviri Uygulaması',
          'My Favorites': 'Favorilerim',
          'Share App': 'Uygulamayı Paylaş',
          'OCR Text Scanner': 'OCR Metin Tarayıcı',
          'Saved': 'kaydedildi',
          'No Text Available Press the button  \n\nto select image':
              'Metin Yok Görüntüyü seçmek için \n\ndüğmeye basın',
          'Translation': 'Tercüme',
          'No Record Found': 'Kayıt Bulunamadı',
          'Text Copied': 'Metin Kopyalandı',
          'Text Cleared': 'Metin Temizlendi',
          'Clear': 'Temizlemek',
          'Text deleted': 'Metin silindi',
          'Added to favorite': 'Favorilere eklendi',
          'Removed from favorite': 'Favoriden kaldırıldı',
          'Next': 'Sonraki',
          'Skip': 'Atlamak',
          'Welcome to Translation Pro': "Çeviri Pro'ya Hoş Geldiniz",
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'Yalnızca birkaç dokunuşla metni birden fazla dile çevirin. İster yurt dışına seyahat ediyor olun, ister başka bir dilde biriyle iletişim kuruyor olun, Translation Pro sizi korur',
          'Scan and Translate': 'Tara ve Çevir',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              ' Görüntülerden ve belgelerden metin çıkarmak ve anında çevirmek için OCR tarayıcımızı kullanın. Bu güçlü özellik işaretleri, menüleri ve diğer metinleri çevirmeyi kolaylaştırır',
          'Conversation Mode': 'Sohbet Modu',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "Farklı bir dil konuşan biriyle görüşmeye mi ihtiyacınız var? Translation Pro'nun konuşma modu, gerçek zamanlı olarak konuşmanıza ve çeviri yapmanıza olanak tanır. Sadece dilleri seçin ve konuşmaya başlayın!"
        },

        // //Indonesian langugae

        'in_ID': {
          'Text Translator': 'Penerjemah Teks',
          'Languages': 'Bahasa',
          'Privacy Policy': 'Kebijakan pribadi',
          'About Us': 'Tentang kami',
          'Contact Us': 'Hubungi kami',
          'Urdu': 'Urdu',
          'English': 'Bahasa inggris',
          'Hindi': 'Hindi',
          'Arabic': 'Arab',
          'Spanish': 'Orang Spanyol',
          'French': 'Perancis',
          'German': 'Jerman',
          'Chinese': 'Cina',
          'Portuguese': 'Portugis',
          'Bengali': 'Benggala',
          'Russian': 'Rusia',
          'Japanese': 'Jepang',
          'Korean': 'Korea',
          'Turkish': 'Turki',
          'Indonesian': 'bahasa Indonesia',
          'Select the language': 'Pilih bahasa',
          'cancel': 'Membatalkan',
          'Select language': 'Pilih bahasa',
          'Write text here': 'Tulis teks di sini',
          'Translate': 'Menerjemahkan',
          'OCR': 'OCR',
          'Speech to Text': 'Ucapan ke Teks',
          'Press the button and start speaking':
              'Tekan tombol dan mulai berbicara',
          'Con': 'Percakapan',
          'Translation App': 'Aplikasi Terjemahan',
          'My Favorites': 'Kesukaanku',
          'Share App': 'Bagikan Aplikasi',
          'OCR Text Scanner': 'Pemindai Teks OCR',
          'Saved': 'Diselamatkan',
          'No Text Available Press the button  \n\nto select image':
              'Tidak Ada Teks yang Tersedia Tekan tombol \n\nuntuk memilih gambar',
          'Translation': 'Terjemahan',
          'No Record Found': 'Tidak Ditemukan Catatan',
          'Text Copied': 'Teks Disalin',
          'Text Cleared': 'Teks Dihapus',
          'Clear': 'Jernih',
          'Text deleted': 'Teks dihapus',
          'Added to favorite': 'Ditambahkan ke favorit',
          'Removed from favorite': 'Dihapus dari favorit',
          'Next': 'Berikutnya',
          'Skip': 'Melewati',
          'Welcome to Translation Pro': 'Selamat datang di Terjemahan Pro',
          'Translate text into multiple with just a few taps. Whether you are traveling abroad or communicating with someone in another language, Translation Pro has got you covered':
              'Terjemahkan teks menjadi banyak hanya dengan beberapa ketukan. Baik Anda bepergian ke luar negeri atau berkomunikasi dengan seseorang dalam bahasa lain, Translation Pro siap membantu Anda',
          'Scan and Translate': 'Pindai dan Terjemahkan',
          'Use our OCR scanner to extract text from images and documents, and translate them instantly. This powerful feature makes it easy to translate signs, menus, and other text':
              'Gunakan pemindai OCR kami untuk mengekstrak teks dari gambar dan dokumen, dan menerjemahkannya secara instan. Fitur canggih ini memudahkan untuk menerjemahkan tanda, menu, dan teks lainnya',
          'Conversation Mode': 'Mode Percakapan',
          "Need to have a conversation with someone who speaks a different language? Translation Pro's conversation mode lets you speak and translate in real-time. Just select the languages and start talking!":
              "Perlu melakukan percakapan dengan seseorang yang berbicara bahasa berbeda? Mode percakapan Terjemahan Pro memungkinkan Anda berbicara dan menerjemahkan dalam waktu nyata. Cukup pilih bahasa dan mulailah berbicara!"
        },
      };
}
